### ISSUE TITLE
Error when installing the package

### ISSUE THREAD

**Issue by KdaerMed2018** [USNavalResearchLaboratory/SNOPROP#2]
Hi, thank you for making public this package
I have Anaconda with python 3.8.8 installed in win 10 environment
I have downloaded the SNOPROP and tried to install it. However the following error message appears :
ERROR: Could not find a version that satisfies the requirement setup
ERROR: No matching distribution found for setup
In the setup file provided with the package, python version >=3.5 <4 is required to install the package.

**Comment by jryan388** [comment]
Hi KdaerMed2018,

Did you try to install the package by running "pip install ." in the
SNOPROP root directory?

**Comment by KdaerMed2018** [comment]
Hi
thank you for your reply
In the first time I tried with the command "pip install setup.py" in the root directory but the installation process failed.
Then I used the command "python setup.py install" and it worked perfectly
Thanks again
